### ISSUE TITLE
安装客户端报错 

### ISSUE THREAD

**Issue by Arler2016** [yafoo/pushme-client#1]
查询相关教程后，添加opengl32.dll后还是无法安装。
(https://telegra.ph/file/9ac1ffc2960b16f9a1241.png)

**Comment by yafoo** [comment]
你的系统是windows几？

**Comment by Arler2016** [comment]
> 你的系统是windows几？

windows 10 家庭版

**Comment by yafoo** [comment]
> > 你的系统是windows几？
> 
> windows 10 家庭版

最新v2.0.0版本使用webview开发，你下载最新版试试
