### ISSUE TITLE
提个新功能

### ISSUE THREAD

**Issue by Crazy-FuQing** [yafoo/pushme-client#2]
作者大大你好，首先感谢你做的这么好的通知套件，比心比心

其次 我也觉得打工人用的最多的还是pc端，最需要的还是在pc端接收到消息。而目前的windows客户端只能接收手机转发的通知，（这方面github上有相对比较成熟的[项目](https://github.com/pppscn/SmsForwarder)、完全可以不用重复造轮子），期待作者大大能考虑这种使用场景，让电脑客户端也能像手机端一样独立接受api消息的功能。万望回复

![image](https://github.com/user-attachments/assets/f3f3df66-c5fb-4668-b07d-ab658f6102ba)

**Comment by yafoo** [comment]
感谢你的喜欢和支持！

从技术上来说，让电脑客户端独立接收消息并不难，不过不想这样做。就像pushme app的简单、轻量一样，我还是喜欢事情简单一点。如果电脑端也能独立接收消息，这样api发消息，就要发两个端，一对一的消息发送，会变成一对多。

手机端接收消息，是为了满足随时随地及时的收到提醒。这个电脑端，也是为了满足专注工作时，可能忽略手机消息的情况，也是为了及时性吧。

你提到的那个项目，最大的作用应该是短信转发，其次是其他消息转发，满足一些特殊场景。理论上，PushMe Client也能接收他转发来的消息。

PushMe Client离独立接收消息，其实只差一个独立IP。如果电脑有独立的IP的话，目前通过给这个IP的3200端口直接发消息，PushMe Client就能接收到的，参数跟api的参数差不多。

你说的电脑端独立接收消息，能说下具体场景吗？

**Comment by Crazy-FuQing** [comment]
> 感谢你的喜欢和支持！
> 
> 从技术上来说，让电脑客户端独立接收消息并不难，不过不想这样做。就像pushme app的简单、轻量一样，我还是喜欢事情简单一点。如果电脑端也能独立接收消息，这样api发消息，就要发两个端，一对一的消息发送，会变成一对多。
> 
> 手机端接收消息，是为了满足随时随地及时的收到提醒。这个电脑端，也是为了满足专注工作时，可能忽略手机消息的情况，也是为了及时性吧。
> 
> 你提到的那个项目，最大的作用应该是短信转发，其次是其他消息转发，满足一些特殊场景。理论上，PushMe Client也能接收他转发来的消息。
> 
> PushMe Client离独立接收消息，其实只差一个独立IP。如果电脑有独立的IP的话，目前通过给这个IP的3200端口直接发消息，PushMe Client就能接收到的，参数跟api的参数差不多。
> 
> 你说的电脑端独立接收消息，能说下具体场景吗？

感谢回复。你提到的“这样api发消息，就要发两个端，一对一的消息发送，会变成一对多” 其实很多时候确实是需要一对多，有些比较重要的通知比如 短信、未接来电、领导消息，都是需要多端通知的，而目前的手机转发到pc端却需要电脑有固定ip，在很多时候带电脑出门连接wifi的场景并不能固定ip，而如果将pc端也作为独立客户端则以上问题迎刃而解

**Comment by yafoo** [comment]
哦，笔记本的话，是个问题，我想想看有没有办法解决

**Comment by Crazy-FuQing** [comment]
> 哦，笔记本的话，是个问题，我想想看有没有办法解决

其实你可以先出一版独立客户端版本，后边在去做轻量化专攻转发也行啊 。将手机端的功能迁移到pc应该不难吧

**Comment by yafoo** [comment]
> > 哦，笔记本的话，是个问题，我想想看有没有办法解决
> 
> 其实你可以先出一版独立客户端版本，后边在去做轻量化专攻转发也行啊 。将手机端的功能迁移到pc应该不难吧

最新的v2.0.0版本，迁移到大部分手机端的功能，支持独立使用，但是仅限连接自建服务独立使用。你要是有自建服务的话，下载最新版试试。
