### ISSUE TITLE
关了3200接口服务就再也连不上了

### ISSUE THREAD

**Issue by imaxhung** [yafoo/pushme-client#4]
自己连自己？默认有没有生成配置文件，在哪里可以改
![image](https://github.com/user-attachments/assets/3a2a5632-c5b3-4089-8813-7b9ab515e20f)

**Comment by yafoo** [comment]
尴尬，这是一个严重的自身逻辑Bug，把自己的服务也给关闭了。

你现在进入C盘用户目录（C:\Users\Administrator\push-me-client），编辑配置文件`setting.json`，把`api->enable`项改为`true`，或者没有重要配置的话，直接把这个文件删除，再启动Pu'shMeClient。

**Comment by imaxhung** [comment]
好滴
