### ISSUE TITLE
断线重连优化

### ISSUE THREAD

**Issue by liesauer** [yafoo/pushme-client#5]
我是直连自建服务器，中午电脑休眠后唤醒，发现数据小屏一直没更新，应该是休眠时断了连接，然后也没重连。

**Comment by yafoo** [comment]
程序默认是会断线重连的，我这里短时间休眠后，测试没有问题。

你再观察一下看看，还是不会重连的话，你在程序主界面，右键点击“检查”，看看控制台有啥错误输出没，有的话，发到这里我看看。

**Comment by liesauer** [comment]
我是笔记本点的关机菜单的休眠，然后关盖午睡去了，两个小时，下午上班就发现10分钟了都没动，我的数据小屏是分钟级推送的。

![image](https://github.com/user-attachments/assets/c6047caa-f8d3-45a0-beea-830f3bd0d0bf)

**Comment by yafoo** [comment]
嗯，在程序主界面右键点击“检查”，然后切换到控制台选项，可以看到消息输出，你观察下，看有啥错误消息没
![image](https://github.com/user-attachments/assets/5f93e07b-a5a6-455f-b85c-87ad13236887)

**Comment by liesauer** [comment]
控制台没任何报错，而且直接断网再联网也是能立马复现出来

54分断网的，55分联网，后面就一直接收不到推送了（常规通知不确定，但数据小屏确实没了）

![image](https://github.com/user-attachments/assets/cc8f6ba4-e878-4ec1-8b90-16b1c57c1582)

**Comment by liesauer** [comment]
> 控制台没任何报错，而且直接断网再联网也是能立马复现出来
> 
> 54分断网的，55分联网，后面就一直接收不到推送了（常规通知不确定，但数据小屏确实没了）
> 
> ![image](https://private-user-images.githubusercontent.com/8676741/378326185-cc8f6ba4-e878-4ec1-8b90-16b1c57c1582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTc4NzcsIm5iZiI6MTcyOTQ5NzU3NywicGF0aCI6Ii84Njc2NzQxLzM3ODMyNjE4NS1jYzhmNmJhNC1lODc4LTRlYzEtOGI5MC0xNmIxYzU3YzE1ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjFUMDc1OTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQxYjhhMDA0Njk5ODg0YzQ3NzkzYjRmZjk1NTgwZGQxNDk3ODZkMTdiOTY4NmNkZTBiZWQ3MDJmODllNmE1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1YXFNuDGGn9JuOqQjjKx9NDFVVOvCrLLt-o9e61hN8c)

好奇怪，刚刚又连上了，但是确实已经等了几分钟了
![image](https://github.com/user-attachments/assets/284d070f-15da-45d3-9ea7-781a194059cd)

**Comment by liesauer** [comment]
我明天中午再试下长时间休眠后唤醒有没有啥错误提示

**Comment by yafoo** [comment]
断线可能有1分钟延迟，重连也可能会有1分钟延迟。控制台一直开着，你再观察观察。

现在系统不支持接收离线消息，你看是否有需要，需要的话，后面加个接收离线消息的选项。

**Comment by yafoo** [comment]
> 我明天中午再试下长时间休眠后唤醒有没有啥错误提示

好的，控制台开着，不要关，方便观察消息。关闭再打开，不会显示历史消息的。

**Comment by liesauer** [comment]
这两天又没发现这种情况了，先关闭，后续再出现的话再开启这个issue。
