### ISSUE TITLE
请求适配小米15（64位应用及HperOS2.0)

### ISSUE THREAD

**Issue by loveitmac** [yafoo/pushme-client#7]
应用在14U上面跑，还算稳定。
在15上面，会经常disconnected和destroy。
希望大佬适配下，感谢。

**Comment by yafoo** [comment]
应该发在 https://github.com/yafoo/pushme 项目下。

pushme app有64位包，你下载64位的试试，试完反馈一下。

**Comment by loveitmac** [comment]
ok，刚刚下错。
一样的，频繁destory和disconnected

雨思 ***@***.***> 于2024年11月4日周一 17:48写道：

**Comment by yafoo** [comment]
zhyaphoo，加我微信明天调试一下吧，我没这手机，没法试。

**Comment by yafoo** [comment]
记录一下：电池开启后台无限制后，问题已解决。
